### ISSUE TITLE
Rounding chart hover-over values

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#439]
When bar chart values have many decimals, it shows ten by default in the hover-over. I'd suggest this should always default to the first decimal at most. 

[](https://unicef-lixil.mwater.co)
![image](https://user-images.githubusercontent.com/5147940/72446989-383ba100-37bd-11ea-9e90-1f2c6bfb666b.png)

**Comment by grassick** [comment]
This is not super-easy, as sometimes the decimals are important and it's hard to tell which in advance.

I've made it so that the Y axis and labels now follow the formatting as defined in the chart (e.g. rounded, currency, etc). Can you give it a try and see if it's good enough? The user would just need to select rounded.
